x-docker-data: &geth-node
  image: ${DOCKER_IMAGE}
  restart: unless-stopped
  network_mode: host
  volumes:
    - data:/data
    - config:/config

services:
  boot:
    <<: *geth-node
    container_name: boot
    profiles: [ "boot", "full-blockchain" ]
    env_file:
      - nodes/.env
      - nodes/boot/.env

  signer:
    <<: *geth-node
    container_name: signer
    profiles: [ "signer", "full-blockchain" ]
    env_file:
      - nodes/.env
      - nodes/signer/.env

  member:
    <<: *geth-node
    profiles: [ "member" ]
    container_name: member
    env_file:
      - nodes/.env
      - nodes/member/.env
    build:
      dockerfile: nodes/member/Dockerfile

  archive:
    <<: *geth-node
    profiles: [ "archive" ]
    container_name: archive
    env_file:
      - nodes/.env
      - nodes/archive/.env

  service:
    <<: *geth-node
    container_name: service
    profiles: [ "service", "full-blockchain" ]
    env_file:
      - nodes/.env
      - nodes/service/.env