x-docker-data: &geth-node
  image: "ghcr.io/rocknitive/geth_c3:main"
  restart: unless-stopped
  network_mode: host
  volumes:
    - data:/data
    - config:/config

services:
  boot-node:
    <<: *geth-node
    container_name: boot-node
    profiles: [ "bootnode", "full-blockchain" ]
    env_file:
      - nodes/.env
      - nodes/boot/.env

  signer-node:
    <<: *geth-node
    container_name: signer-node
    profiles: [ "signer-node", "full-blockchain" ]
    env_file:
      - nodes/.env
      - nodes/signer/.env

  member-node:
    <<: *geth-node
    profiles: [ "member-node" ]
    container_name: member-node
    env_file:
      - nodes/.env
      - nodes/member/.env
    build:
      dockerfile: nodes/member/Dockerfile

  archive-node:
    <<: *geth-node
    profiles: [ "archive-node" ]
    env_file:
      - nodes/.env
      - nodes/archive/.env
    container_name: archive-node

  service-node:
    <<: *geth-node
    container_name: service-node
    profiles: [ "service-node", "full-blockchain" ]
    env_file:
      - nodes/.env
      - nodes/service/.env