version: '3.8'
services:
  init:
    profiles: ["cli"]
    image: alpine
    command:
      - /bin/sh
      - -c
      - |
        chown -R 1000:1000 /data

        echo "done granting data directory permission"
    volumes:
      - data:/data

  geth-cli:
    profiles: ["cli"]
    build:
      context: ..
      dockerfile: docker/cli/Dockerfile
    container_name: geth-cli
    network_mode: host
    restart: "no"
    volumes:
      - data:/data
      - config:/config

volumes:
  config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${MOUNT_DIR}/config/${NETWORK}
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${MOUNT_DIR}/data/${NETWORK}